apiVersion: batch/v1
kind: Job
metadata:
  name: devstats-backfill
  namespace: default
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: devstats-backfill
        image: gcr.io/devstats-gke/devstats:latest
        imagePullPolicy: Always
        workingDir: "/mount/data/src/test-infra/devstats"
        command: ["gha2db", "2019-03-22", "0", "`date +%Y-%m-%d`", "23", "knative"]
        envFrom:
        - configMapRef:
            name: devstats-env
        env:
        - name: PG_PASS
          valueFrom:
            secretKeyRef:
              name: gha-admin-pass
              value: pg_gha_admin_password
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: gha-admin-pass
              value: pg_gha_admin_password
        volumeMounts:
        - mountPath: "/mount/data"
          name: "nfs"
      terminationGracePeriodSeconds: 10
      volumes:
      - name: "nfs"
        persistentVolumeClaim:
          claimName: "devstats-claim"
