apiVersion: batch/v1
kind: Job
metadata:
  name: devstats-backfill
  namespace: default
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: devstats-backfill
        image: gcr.io/devstats-gke/devstats:latest
        imagePullPolicy: Always
        workingDir: "/mount/data/src/test-infra/devstats"
        command: ["gha2db", "2019-03-22", "0", "2019-05-02", "19", "knative"]
        envFrom:
        - configMapRef:
            name: devstats-env
        volumeMounts:
        - mountPath: "/mount/data"
          name: "nfs"
      terminationGracePeriodSeconds: 10
      volumes:
      - name: "nfs"
        persistentVolumeClaim:
          claimName: "devstats-claim"
