# cron job for populating the database hourly
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: devstats-cron
  namespace: devstats-postgres
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: devstats-cron
            image: gcr.io/devstats-gke/devstats:latest
            workingDir: "/mount/data/src/devstats"
            command: ["devstats",]
            env:
            - name: PG_HOST
              value: "postgres-db-0.postgres-db.devstats-postgres.svc.cluster.local"
            - name: PG_DB
              value: "knative"
            - name: PG_PASS
              value: "password"
            - name: PG_PASS_ROLE
              value: "ro_user"
      # Specific to Postgres
            - name: PGHOST
              value: "postgres-db-0.postgres-db.devstats-postgres.svc.cluster.local"
            - name: PGDATABASE
              value: "knative"
            - name: PGUSER
              value: "gha_admin"
            - name: PGPASSWORD
              value: "password"
            - name: GHA2DB_PROJECT
              value: "projects.yaml"
            - name: GHA2DB_REPOS_DIR
              value: "/mount/data/devstats_repos"
            volumeMounts:
            - mountPath: "/mount/data"
              name: "nfs"
          terminationGracePeriodSeconds: 10
          volumes:
          - name: "nfs"
            persistentVolumeClaim:
              claimName: "devstats-recreate"

