# cron job for populating the database hourly
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: devstats-cron
  namespace: devstats-postgres
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: devstats-cron
            image: gcr.io/devstats-gke/devstats:latest
            imagePullPolicy: Always
            workingDir: "/mount/data/src/devstats"
            command: ["devstats",]
            envFrom:
            - configMapRef:
                name: devstats-env
            volumeMounts:
            - mountPath: "/mount/data"
              name: "nfs"
          terminationGracePeriodSeconds: 10
          volumes:
          - name: "nfs"
            persistentVolumeClaim:
              claimName: "devstats-recreate"

