apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: devstats-postgres
spec:
  ports:
  - protocol: "TCP"
    port: 3000
  selector:
    app: grafana
  type: "NodePort"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: devstats-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: grafana/grafana
        imagePullPolicy: IfNotPresent
        name: grafana
        ports:
        - containerPort: 3000
        env:
        - name: GF_PATHS_DATA
          value: "/mount/data/grafana"
        - name: GF_PATHS_PROVISIONING
          value: "/mount/data/src/devstats/grafana/provisioning"
     # - name: seecret
     # todo - fill in secret value
        volumeMounts:
        - mountPath: "/mount/data"
          name: "nfs"
      volumes:
      - name: "nfs"
        persistentVolumeClaim:
          claimName: "devstats-nfs"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: devstats-postgres
  #annotations:
spec:
  rules:
    #host: you should be able to set up knative.dev here
  - http:
      paths:
      - path: "/*"
        backend:
          serviceName: grafana
          servicePort: 3000
