---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: devstats-recreate
  namespace: devstats-postgres
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1000Gi
  nfs:
    # This should be the name of the fileshare in cloud filestore
    path: /devstats4nfs
    server: 10.160.187.114
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devstats-recreate
  namespace: devstats-postgres
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-storage
  volumeName: devstats-recreate
